version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ca-central-1"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Entered the install phase...
      - npm install
      - npm install serverless
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npx serverless deploy -v